// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const rawUrl = import.meta.env.VITE_SUPABASE_URL;
const rawKey = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const isConfigured = Boolean(
  rawUrl &&
  rawKey &&
  !rawUrl.includes('placeholder') &&
  rawUrl.startsWith('http')
);

// Fallback in-memory and localStorage storage
const getStorageKey = (table: string) => `mock_sb_${table}`;
const getTableData = (table: string): any[] => {
  try {
    const raw = localStorage.getItem(getStorageKey(table));
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
};
const setTableData = (table: string, data: any[]) => {
  try {
    localStorage.setItem(getStorageKey(table), JSON.stringify(data));
  } catch {
    // quota exceeded or memory only
  }
};

const DEFAULT_USER = {
  id: '00000000-0000-0000-0000-000000000001',
  aud: 'authenticated',
  role: 'authenticated',
  email: 'demo@example.com',
  email_confirmed_at: new Date().toISOString(),
  phone: '',
  confirmed_at: new Date().toISOString(),
  last_sign_in_at: new Date().toISOString(),
  app_metadata: { provider: 'email', providers: ['email'] },
  user_metadata: { name: 'المستخدم التجريبي' },
  identities: [],
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

const DEFAULT_SESSION = {
  access_token: 'mock-access-token',
  token_type: 'bearer',
  expires_in: 3600,
  refresh_token: 'mock-refresh-token',
  user: DEFAULT_USER,
  expires_at: Math.floor(Date.now() / 1000) + 3600,
};

const getStoredSession = () => {
  try {
    const raw = localStorage.getItem('mock_sb_session');
    if (raw) return JSON.parse(raw);
  } catch {}
  return DEFAULT_SESSION;
};

const authListeners = new Set<(event: string, session: any) => void>();

const mockAuth = {
  onAuthStateChange: (callback: (event: string, session: any) => void) => {
    authListeners.add(callback);
    const session = getStoredSession();
    setTimeout(() => {
      if (authListeners.has(callback)) {
        callback(session ? 'SIGNED_IN' : 'SIGNED_OUT', session);
      }
    }, 0);
    return {
      data: {
        subscription: {
          unsubscribe: () => {
            authListeners.delete(callback);
          },
        },
      },
    };
  },
  getSession: async () => {
    const session = getStoredSession();
    return { data: { session }, error: null };
  },
  getUser: async () => {
    const session = getStoredSession();
    return { data: { user: session?.user ?? null }, error: null };
  },
  signInWithPassword: async ({ email }: { email: string; password?: string }) => {
    const user = {
      ...DEFAULT_USER,
      email: email || 'demo@example.com',
    };
    const session = {
      ...DEFAULT_SESSION,
      user,
    };
    try {
      localStorage.setItem('mock_sb_session', JSON.stringify(session));
    } catch {}
    authListeners.forEach((cb) => cb('SIGNED_IN', session));
    return { data: { user, session }, error: null };
  },
  signUp: async ({ email }: { email: string; password?: string }) => {
    return mockAuth.signInWithPassword({ email });
  },
  signOut: async () => {
    try {
      localStorage.removeItem('mock_sb_session');
    } catch {}
    authListeners.forEach((cb) => cb('SIGNED_OUT', null));
    return { error: null };
  },
};

const createMockQueryBuilder = (tableName: string) => {
  const filters: Array<(item: any) => boolean> = [];
  let sortFn: ((a: any, b: any) => number) | null = null;
  let limitCount: number | null = null;
  let isSingle = false;
  let isMaybeSingle = false;

  let pendingOperation: (() => any) | null = null;

  const builder: any = {
    select: () => {
      return builder;
    },
    insert: (values: any) => {
      pendingOperation = () => {
        const rows = Array.isArray(values) ? values : [values];
        const current = getTableData(tableName);
        const inserted = rows.map((r) => ({
          id: r.id || crypto.randomUUID(),
          created_at: r.created_at || new Date().toISOString(),
          updated_at: new Date().toISOString(),
          ...r,
        }));
        setTableData(tableName, [...current, ...inserted]);
        return Array.isArray(values) ? inserted : inserted[0];
      };
      return builder;
    },
    upsert: (values: any, options?: any) => {
      pendingOperation = () => {
        const rows = Array.isArray(values) ? values : [values];
        const current = getTableData(tableName);
        const onConflict = options?.onConflict || 'id';
        const updated = [...current];

        const insertedOrUpdated = rows.map((row) => {
          const item = {
            id: row.id || crypto.randomUUID(),
            created_at: row.created_at || new Date().toISOString(),
            updated_at: new Date().toISOString(),
            ...row,
          };
          const existingIndex = updated.findIndex((r) => r[onConflict] === item[onConflict]);
          if (existingIndex >= 0) {
            updated[existingIndex] = { ...updated[existingIndex], ...item };
            return updated[existingIndex];
          } else {
            updated.push(item);
            return item;
          }
        });
        setTableData(tableName, updated);
        return Array.isArray(values) ? insertedOrUpdated : insertedOrUpdated[0];
      };
      return builder;
    },
    update: (updates: any) => {
      pendingOperation = () => {
        const current = getTableData(tableName);
        const updated = current.map((item) => {
          if (filters.every((f) => f(item))) {
            return { ...item, ...updates, updated_at: new Date().toISOString() };
          }
          return item;
        });
        setTableData(tableName, updated);
        return updated.filter((item) => filters.every((f) => f(item)));
      };
      return builder;
    },
    delete: () => {
      pendingOperation = () => {
        const current = getTableData(tableName);
        const remaining = current.filter((item) => !filters.every((f) => f(item)));
        setTableData(tableName, remaining);
        return [];
      };
      return builder;
    },
    eq: (column: string, value: any) => {
      filters.push((item) => String(item[column]) === String(value));
      return builder;
    },
    neq: (column: string, value: any) => {
      filters.push((item) => String(item[column]) !== String(value));
      return builder;
    },
    in: (column: string, values: any[]) => {
      const set = new Set(values.map((v) => String(v)));
      filters.push((item) => set.has(String(item[column])));
      return builder;
    },
    order: (column: string, options?: { ascending?: boolean }) => {
      const asc = options?.ascending !== false;
      const prevSort = sortFn;
      sortFn = (a: any, b: any) => {
        if (prevSort) {
          const res = prevSort(a, b);
          if (res !== 0) return res;
        }
        if (a[column] === b[column]) return 0;
        if (a[column] == null) return asc ? -1 : 1;
        if (b[column] == null) return asc ? 1 : -1;
        return (a[column] > b[column] ? 1 : -1) * (asc ? 1 : -1);
      };
      return builder;
    },
    limit: (count: number) => {
      limitCount = count;
      return builder;
    },
    single: () => {
      isSingle = true;
      return builder;
    },
    maybeSingle: () => {
      isMaybeSingle = true;
      return builder;
    },
    then: (onfulfilled?: (res: any) => any, onrejected?: (err: any) => any) => {
      let resultData: any;
      if (pendingOperation) {
        resultData = pendingOperation();
      } else {
        let items = getTableData(tableName);
        if (filters.length > 0) {
          items = items.filter((item) => filters.every((f) => f(item)));
        }
        if (sortFn) {
          items.sort(sortFn);
        }
        if (limitCount != null) {
          items = items.slice(0, limitCount);
        }
        resultData = items;
      }

      if (isSingle) {
        resultData = Array.isArray(resultData) ? (resultData[0] || null) : resultData;
      } else if (isMaybeSingle) {
        resultData = Array.isArray(resultData) ? (resultData[0] || null) : resultData;
      }

      const response = { data: resultData, error: null };
      return Promise.resolve(response).then(onfulfilled, onrejected);
    },
  };

  return builder;
};

const mockStorage = {
  from: (bucket: string) => ({
    upload: async (filePath: string, file: any) => {
      const reader = new FileReader();
      const promise = new Promise<string>((resolve) => {
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = () => resolve("");
        if (file instanceof Blob) {
          reader.readAsDataURL(file);
        } else {
          resolve("");
        }
      });
      const dataUrl = await promise;
      try {
        localStorage.setItem(`mock_storage_${bucket}_${filePath}`, dataUrl);
      } catch {}
      return { data: { path: filePath }, error: null };
    },
    getPublicUrl: (filePath: string) => {
      const dataUrl = localStorage.getItem(`mock_storage_${bucket}_${filePath}`) || "";
      return { data: { publicUrl: dataUrl } };
    },
    createSignedUrl: async (filePath: string) => {
      const dataUrl = localStorage.getItem(`mock_storage_${bucket}_${filePath}`) || "";
      return { data: { signedUrl: dataUrl }, error: null };
    },
    remove: async (paths: string[]) => {
      paths.forEach((p) => {
        try {
          localStorage.removeItem(`mock_storage_${bucket}_${p}`);
        } catch {}
      });
      return { data: paths, error: null };
    },
  }),
};

const mockSupabaseClient = {
  auth: mockAuth,
  from: createMockQueryBuilder,
  storage: mockStorage,
};

export const supabase = (
  isConfigured
    ? createClient<Database>(rawUrl, rawKey, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (mockSupabaseClient as unknown as ReturnType<typeof createClient<Database>>)
);
